FROM ubuntu:24.04

ARG userid
ARG groupid
ARG username
ARG DEBIAN_FRONTEND=noninteractive

ENV LANG=en_US.UTF-8

RUN apt-get update && apt-get -y upgrade

# Essential Yocto Project host packages are:
RUN apt-get update
RUN apt-get install -y gawk wget git diffstat unzip texinfo gcc-multilib \
          build-essential chrpath socat cpio python3 python3-pip python3-pexpect \
          xz-utils debianutils iputils-ping python3-git python3-jinja2 libegl-mesa0 libsdl2-dev \
          xterm rsync util-linux bsdextrautils curl zstd lz4 python3-subunit mesa-common-dev liblz4-tool file

# Additional host packages required by poky/scripts/wic
RUN apt-get install -y curl dosfstools mtools parted syslinux tree tzdata vim libtool libsdl2-2.0-0

# Add "repo" tool (used by many Yocto-based projects)
RUN curl http://storage.googleapis.com/git-repo-downloads/repo > /usr/local/bin/repo
RUN chmod a+x /usr/local/bin/repo

RUN apt-get install -y git fakeroot libncurses5-dev libssl-dev ccache lzop

RUN apt-get install -y locales
RUN dpkg-reconfigure locales
RUN locale-gen en_US.UTF-8
RUN update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8

# Create a non-root user that will perform the actual build (if needed)
RUN apt-get install -y sudo
RUN set -eux; \
    \
    # Group
    if ! getent group ${groupid} >/dev/null; then \
        groupadd -g ${groupid} ${username}; \
    fi; \
    \
    # User
    if ! getent passwd ${userid} >/dev/null; then \
        useradd -m -u ${userid} -g ${groupid} -s /bin/bash ${username}; \
    else \
        existing_user=$(getent passwd ${userid} | cut -d: -f1); \
        if [ "${existing_user}" != "${username}" ]; then \
            usermod -l ${username} ${existing_user}; \
            usermod -d /home/${username} -m ${username}; \
        fi; \
    fi; \
    \
    echo "${username} ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/${username} && \
    chmod 0440 /etc/sudoers.d/${username}

ENV HOME=/home/${username}
ENV USER=${username}

ENTRYPOINT ["/bin/bash"]

# EOF
